spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin_practice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: "JIWGOeJsf7oE1YLs9ClVrY6tVAclJMwV3mF3NYUiIkKMVK2qlXyYT3u_npMLinYY"
    expiration-seconds: 360000
